WebShop/src/main/java/com/epam/storozhuk/entity/Cart.java
package com.epam.storozhuk.entity;

import java.math.BigDecimal;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class Cart {
    private Map<Product, Integer> cartProducts;

    public Cart() {
        initMap();
    }

    public Cart(Product product, int amount) {
        initMap();
        cartProducts.put(product, amount);
    }

    public Cart(List<Product> productsList, List<Integer> amountsList) {
        initMap();
        int index = 0;
        for (Product product : productsList) {
            cartProducts.put(product, amountsList.get(index++));
        }
    }

    public Cart(Map<Product, Integer> cartProducts) {
        initMap();
        this.cartProducts = new LinkedHashMap<>(cartProducts);
    }

    public Map<Product, Integer> getCartProducts() {
        return cartProducts;
    }

    public BigDecimal getSummaryPrice() {
        BigDecimal sum = new BigDecimal(0);
        BigDecimal multiply = new BigDecimal(0);
        for (Product product : cartProducts.keySet()) {
            multiply = multiply.add(new BigDecimal(cartProducts.get(product)).multiply(product.getPrice()));
            sum = sum.add(multiply);
        }
        return sum;
    }

    public int getSummaryProductsAmount() {
        int sum = 0;
        for (Product product : cartProducts.keySet()) {
            sum += cartProducts.get(product);
        }
        return sum;
    }

    public void removeProduct(int id) {
        for (Product product : cartProducts.keySet()) {
            if (product.getProductId() == id) {
                cartProducts.remove(product);
                break;
            }
        }
    }

    public void addProduct(Product product, int amount) {
        cartProducts.put(product, amount);
    }

    private void initMap() {
        cartProducts = new LinkedHashMap<>();
    }
}

WebShop/src/main/java/com/epam/storozhuk/servlet/cart/AddProductToCartServlet.java
package com.epam.storozhuk.servlet.cart;

import com.epam.storozhuk.constant.Const;
import com.epam.storozhuk.entity.Cart;
import com.epam.storozhuk.entity.Product;
import com.epam.storozhuk.service.ProductService;
import org.apache.log4j.Logger;

import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.util.Map;

@WebServlet("/addProductToCart")
public class AddProductToCartServlet extends HttpServlet {
    private static final Logger LOGGER = Logger.getLogger(AddProductToCartServlet.class);
    private ProductService productService;

    @Override
    public void init() {
        productService = (ProductService) getServletContext().getAttribute(Const.PRODUCT_SERVICE);
    }

    public void doGet(HttpServletRequest request, HttpServletResponse response) {
        Cart cart = (Cart) request.getSession().getAttribute(Const.CART_PARAMETER);
        if (cart == null) {
            LOGGER.debug("Cart is null. Creating new cart");
            cart = new Cart();
        }
        String id = request.getParameter(Const.PRODUCT_ID_PARAM);
        if (cartContainsProduct(cart, id)) {
            LOGGER.debug("Cart already has necessary product. Increasing it's amount");
            incrementProductAmount(cart.getCartProducts(), id);
        } else {
            LOGGER.debug("Cart doesn't contain necessary product. Adding it to cart");
            Product product = productService.getProductById(Integer.parseInt(id));
            if (product != null) {
                LOGGER.debug("Successfully received product by id. Adding it to the carts list");
                cart.addProduct(product, 1);
            }
        }
        request.getSession().setAttribute(Const.CART_PARAMETER, cart);
    }

    private void incrementProductAmount(Map<Product, Integer> cartMap, String id) {
        int id_num = Integer.parseInt(id);
        for (Product product : cartMap.keySet()) {
            if (product.getProductId() == id_num) {
                cartMap.put(product, cartMap.get(product) + 1);
                return;
            }
        }
    }

    private boolean cartContainsProduct(Cart cart, String id) {
        int id_num = Integer.parseInt(id);
        boolean contains = false;
        for (Product product : cart.getCartProducts().keySet()) {
            if (product.getProductId() == id_num) {
                contains = true;
                break;
            }
        }
        return contains;
    }
}

WebShop/src/main/java/com/epam/storozhuk/servlet/cart/ClearCartServlet.java
package com.epam.storozhuk.servlet.cart;

import com.epam.storozhuk.constant.Const;
import com.epam.storozhuk.entity.Cart;

import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/clearCart")
public class ClearCartServlet extends HttpServlet {

    public void doGet(HttpServletRequest request, HttpServletResponse response) {
        request.getSession().setAttribute(Const.CART_PARAMETER, new Cart());
        response.setStatus(200);
    }
}

WebShop/src/main/java/com/epam/storozhuk/servlet/cart/DecrementProductAmountServlet.java
package com.epam.storozhuk.servlet.cart;

import com.epam.storozhuk.constant.Const;
import com.epam.storozhuk.entity.Cart;
import com.epam.storozhuk.entity.Product;
import org.apache.log4j.Logger;

import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.util.Map;

@WebServlet("/decrementAmount")
public class DecrementProductAmountServlet extends HttpServlet {
    public static final Logger LOGGER = Logger.getLogger(DecrementProductAmountServlet.class);

    public void doGet(HttpServletRequest request, HttpServletResponse response) {
        String id = request.getParameter(Const.PRODUCT_ID_PARAM);
        Cart cart = (Cart) request.getSession().getAttribute(Const.CART_PARAMETER);
        decrementProductAmount(cart.getCartProducts(), id);
        response.setStatus(200);
    }

    private void decrementProductAmount(Map<Product, Integer> cartMap, String id) {
        int id_num = Integer.parseInt(id);
        for (Product product : cartMap.keySet()) {
            if (product.getProductId() == id_num) {
                LOGGER.debug("Found product which amount to increment");
                cartMap.put(product, cartMap.get(product) - 1);
                return;
            }
        }
    }
}

WebShop/src/main/java/com/epam/storozhuk/servlet/cart/IncrementProductAmountServlet.java
package com.epam.storozhuk.servlet.cart;

import com.epam.storozhuk.constant.Const;
import com.epam.storozhuk.entity.Cart;
import com.epam.storozhuk.entity.Product;
import com.epam.storozhuk.service.CartService;
import org.apache.log4j.Logger;

import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.util.Map;

@WebServlet("/incrementAmount")
public class IncrementProductAmountServlet extends HttpServlet {
    public static final Logger LOGGER = Logger.getLogger(IncrementProductAmountServlet.class);
    private CartService cartService;

    @Override
    public void init() {
        cartService = (CartService) getServletContext().getAttribute(Const.CART_SERVICE);
    }

    public void doGet(HttpServletRequest request, HttpServletResponse response) {
        String id = request.getParameter(Const.PRODUCT_ID_PARAM);
        Cart cart = (Cart) request.getSession().getAttribute(Const.CART_PARAMETER);
        incrementProductAmount(cart.getCartProducts(), id);
        response.setStatus(200);
    }

    private void incrementProductAmount(Map<Product, Integer> cartMap, String id) {
        int id_num = Integer.parseInt(id);
        for (Product product : cartMap.keySet()) {
            if (product.getProductId() == id_num) {
                LOGGER.debug("Found product which amount to increment");
                cartMap.put(product, cartMap.get(product) + 1);
                return;
            }
        }
    }
}

WebShop/src/main/java/com/epam/storozhuk/servlet/cart/RemoveProductFromCartServlet.java
package com.epam.storozhuk.servlet.cart;

import com.epam.storozhuk.constant.Const;
import com.epam.storozhuk.entity.Cart;
import com.epam.storozhuk.entity.Product;
import com.epam.storozhuk.service.CartService;
import org.apache.log4j.Logger;

import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.util.Map;

@WebServlet("/removeFromCart")
public class RemoveProductFromCartServlet extends HttpServlet {
    private static final Logger LOGGER = Logger.getLogger(RemoveProductFromCartServlet.class);
    private CartService cartService;

    @Override
    public void init() {
        cartService = (CartService) getServletContext().getAttribute(Const.CART_SERVICE);
    }

    public void doGet(HttpServletRequest request, HttpServletResponse response) {
        Cart cart = (Cart) request.getSession().getAttribute(Const.CART_PARAMETER);
        String id = request.getParameter(Const.PRODUCT_ID_PARAM);
        removeProduct(cart.getCartProducts(), id);
        response.setStatus(200);
    }

    private void removeProduct(Map<Product, Integer> cartMap, String id) {
        int id_num = Integer.parseInt(id);
        for (Product product : cartMap.keySet()) {
            if (product.getProductId() == id_num) {
                LOGGER.debug("Found product to remove");
                cartMap.remove(product);
                return;
            }
        }
    }
}

WebShop/src/main/webapp/pages/cart/cart.jsp
<!DOCTYPE HTML>
<%@ taglib prefix = "c" uri = "http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="tags" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<fmt:setLocale value="${pageContext.request.locale.language}"/>
<fmt:setBundle basename="words"/>
<html>

<head>
  <title>Login Page</title>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8"><title>W3.CSS Template</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="../../styles/w3.css">
  <link rel="stylesheet" href="../../styles/css.css">
  <link rel="stylesheet" href="../../styles/font-awesome.css">
  <script src="../../js/jquery/jquery_3.4.1.js"></script>
  <script src="../../js/cart_list.js"></script>
  <style>
    body,h1,h2,h3,h4,h5,h6 {font-family: "Karma", sans-serif}
    .w3-bar-block .w3-bar-item {padding:20px}
    </style>
</head>
<c:set var="cartList" value="${cart}"/>
<body>
<c:if test="${not empty cartList.cartProducts}">
   <div style="z-index:2; overflow-y:hidden; border:1px solid black; width:340px; height:340px; position:fixed; display:none; background-color:white; margin-left:25%;" name="cartOrder">
   <span onclick="closeOrder();" style="float:right; margin-right: 4px;">X</span>
    <br/>
    <iframe name="makeOrder_frame" style="width:-webkit-fill-available; height:-webkit-fill-available;">
    </iframe>
   </div>
   <table style="width:100%; text-align:center;">
   <tr>
   <th><fmt:message key="mark"/></th>
   <th><fmt:message key="model"/></th>
   <th><fmt:message key="prod_year"/></th>
   <th><fmt:message key="price"/></th>
   <th><fmt:message key="amount"/></th>
   <tr>
   <c:forEach items="${cartList.cartProducts}" var="item">
   <tr>
      <td>${item.key.mark}</td>
      <td>${item.key.model}</td>
      <td>${item.key.productionYear}</td>
      <td>${item.key.price}</td>
      <td><span onclick="decrementAmount(${item.key.productId}, ${item.key.price})" style="margin-right:4px; font-size:25px;">-</span><span id="span_${item.key.productId}">${item.value}</span><span onclick="incrementAmount(${item.key.productId}, ${item.key.price})" style="margin-left:4px; font-size:25px;">+</span></td>
      <td><span style="font-size:23px;" onclick="removeProduct(${item.key.productId})">X</span></td>
   </tr>
   </c:forEach>
   </table>
   <fmt:message key="sum_prod_amount"/>: <span id="amountSum">${cartList.summaryProductsAmount}</span>
   <br/>
   <fmt:message key="sum_price"/>: <span id="priceSum">${cartList.summaryPrice}</span>
   <br/>
   <button onclick="clearCart();" style="margin-left: 4px;"><fmt:message key="clear_cart"/></button>
   <br/>
   <button onclick="getOrderCart();" style="margin-left: 4px; margin-top:1%;"><fmt:message key="make_order"/></button>
   <input type="hidden" id="login" value="${userState}"/>
</c:if>
<c:if test="${empty cartList.cartProducts}">
<p style="text-align: center; margin-top:10%; font-size: 25px;"><fmt:message key="empty_cart"/></p>
</c:if>
</body>
</html>

WebShop/src/main/webapp/pages/cart/order_cart.jsp
<!DOCTYPE HTML>
<%@ taglib prefix = "c" uri = "http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="tags" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<fmt:setLocale value="${pageContext.request.locale.language}"/>
<fmt:setBundle basename="words"/>
<html>

<head>
  <title>Login Page</title>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8"><title>W3.CSS Template</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="../../styles/w3.css">
  <link rel="stylesheet" href="../../styles/css.css">
  <link rel="stylesheet" href="../../styles/font-awesome.css">
  <script src="../../js/jquery/jquery_3.4.1.js"></script>
  <script src="../../js/cart_list.js"></script>
  <style>
    body,h1,h2,h3,h4,h5,h6 {font-family: "Karma", sans-serif}
    .w3-bar-block .w3-bar-item {padding:20px}
    </style>
</head>
<body>
<form name="applyOrder" method="post" onsubmit="return submitOrder();" style="text-align:center;" action="/applyOrder"/>
<fmt:message key="receiver_initials"/><br/><input type="text" name="receiverName"/><br/>
<p id="name_error" style="display:none; color:red;">Wrong name value<br/></p>
<fmt:message key="payment"/><br/>
<select name="payment" onchange="getPayment();">
<option value="Cash payment"><fmt:message key="cash_payment"/></option>
<option value="Bank card"><fmt:message key="bank_card"/></option>
</select>
<br/>
<span id="card_info" style="display:none;"><fmt:message key="card_number"/><br/><input type="number" name="cardNumber"/><br/>
<p id="card_info_error" style="display:none; font-color:red;">Wrong card number<br/></p>
CVV<br/><input type="number" name="cvv"/><br/>
<p id="cvv_error" style="display:none; font-color:red;">Wrong CVV code</p>
<fmt:message key="exp_date"/><br/><input type="number" name="month" style="margin-right:2px;width:10%;"/><input type="number" name="year" style="width:20%;"/><br/>
<p id="date_error" style="display:none; font-color:red;">Wrong expiration date</p>
</span>
<input type="submit" value=<fmt:message key="apply_order"/>/>
</form>
</body>
</html>